# Generated by Django 3.2.3 on 2021-05-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20210530_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='notified_contacts',
            field=models.ManyToManyField(related_name='notification_meetings', to='meetings.Contact'),
        ),
    ]
